### ISSUE TITLE
Make a converter for TOML -> sublime and/or vscode snippets

### ISSUE THREAD

**Issue by Robbie-Cook** [CloudCannon/cloudcannon-snippets#1]
To make the same snippet avaliable across Sublime and VSCode, it would be great to draw the data from a TOML file, and create VSCode and Sublime snippets from it.

E.g.

```toml
title = "Jekyll Snippet"
type = "html"

snippet = '''
<div class="c-${ComponentName}"></div>
'''
```
